/*
 * Published site content for index.html (edited in admin.html).
 * Replace this file on the server to publish changes.
 * Any text may contain {commission}, which is replaced by the commission value,
 * and {year}, which is replaced by the current year.
 */
window.SITE_DEFAULTS = {
  "commission": 70,
  "seo": {
    "title": "Teen Patti Agent – Earn {commission}% Commission | Teen Patti Stars",
    "description": "Earn up to {commission}% commission as a Teen Patti Agent. Join 10,000+ agents across India. Free to join and instant withdrawals. Start earning today.",
    "siteUrl": "https://agents.teenpattistars.io"
  },
  "header": {
    "downloadLabel": "DOWNLOAD GAME",
    "downloadUrl": "https://bit.ly/4iwW8FR"
  },
  "menu": [
    { "label": "About Agency", "url": "#agency-plan" },
    { "label": "Why Join", "url": "#agency-benefit" },
    { "label": "How To Join", "url": "#how-to-join" },
    { "label": "Big Agent India", "url": "/big-agent-india/" },
    { "label": "Steps", "url": "#how-it-works" }
  ],
  "hero": {
    "headline": {
      "before": "Teen Patti Stars",
      "highlight": "Earn up to {commission}%",
      "after": "Commission"
    },
    "joinLabel": "JOIN NOW",
    "joinUrl": "#how-to-join",
    "downloadLabel": "DOWNLOAD GAME",
    "mobileLabel": "START TO EARN",
    "slides": [
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/banner3.webp", "alt": "Teen Patti Stars agent beside the Nation's Trusted online gaming app badge" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/tps-agency-plan-962-by-565-recolor-1.webp", "alt": "Agency plan commission: earn up to 30% to 70%" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/958-by-662-pixels-1.webp", "alt": "Nation's Trusted online gaming app badge" }
    ]
  },
  "features": [
    { "icon": "💸", "title": "High Commission", "text": "Earn up to {commission}% revenue share with transparent, real-time payouts." },
    { "icon": "⚡", "title": "Instant Withdrawals", "text": "Quick and secure settlements for agents and partners across India." },
    { "icon": "🏆", "title": "Trusted Network", "text": "Join a fast-growing community of agents serving 10,000+ players." }
  ],
  "steps": {
    "title": "How to install Teen Patti Stars APK",
    "items": [
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-Step1-253x450.webp", "alt": "Phone screenshot for step 1", "text": "Visit Teen Patti Stars official website using your Android mobile and tap the \"Download App\" button to get the Teen Patti Stars APK file." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-step2-253x450.webp", "alt": "Phone screenshot for step 2", "text": "After clicking the \"Download App\" button you may get a warning message on your screen. It is a default feature of Android smartphones to ensure device safety and protection from viruses. However, the Teen Patti Stars app is absolutely safe. So tap the \"Download Anyway\" button to start the download" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-step3-253x450.webp", "alt": "Phone screenshot for step 3", "text": "Now open the APK file from the drop down/notification panel to start the installation process." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-Step4-1-253x450.webp", "alt": "Phone screenshot for step 4", "text": "Tap the \"Install\" button for installing the app on your mobile device. No special access is required to install the app." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-Step5-253x450.webp", "alt": "Phone screenshot for step 5", "text": "Once the Teen Patti Stars app is successfully installed in your mobile, tap the \"open\" button." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/08/Teen-step6-253x450.webp", "alt": "Phone screenshot for step 6", "text": "You are all set! Start playing Teen Patti Stars games to win exciting prizes." }
    ]
  },
  "agencyPlan": {
    "title": "Big Agency Plan",
    "intro": "Receive payouts and incentives based on the bets made by players you recommend. You will make more money if you recommend more gamers and they wager larger amounts.",
    "highlights": [
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools.webp", "alt": "", "text": "Monthly income of one million with unlimited surprises. Teach you step by step how to make money" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-1.webp", "alt": "", "text": "You will receive commission based on net profits generated by the players you have recommended" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools.webp", "alt": "", "text": "The number of players you’ve referred and your earnings can both be monitored by a systemized platform" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-2.webp", "alt": "", "text": "This website contains your unique code, which allows your visitors to access the Teen Patti Stars website" }
    ],
    "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/tps-agency-plan-639-by-458-1.webp",
    "imageAlt": "Agency plan commission: earn up to 30% to 70%",
    "howTitle": "How it works",
    "steps": [
      { "label": "Download Game:", "text": "Download the game and install, get your exclusive link and share it with friends" },
      { "label": "Sign Up:", "text": "Join our elite group of partners." },
      { "label": "Refer Players:", "text": "Connect Players with our top-notch services." },
      { "label": "Earn Commissions:", "text": "Watch your earnings grow with every successful collaboration." }
    ],
    "notes": [
      { "text": "For example: if A is a big agent, all it’s subordinate members lose a total of 1000RS, and the cost of the three items is 200RS." },
      { "text": "The negative profit sharing ration is 50%, then A wins: [(1000RS – 200RS)*50%]= 400RS" }
    ],
    "buttonLabel": "Download Game"
  },
  "agencyBenefit": {
    "title": "Agency Benefit",
    "items": [
      { "title": "Sharing Benefit", "text": "By referring friends, you can both enjoy the excitement of gaming and jointly gain access to exclusive benefits. It’s a cooperative adventure filled with thrills and bonuses rather than just a game." },
      { "title": "Weekly Bonus", "text": "With each friend you introduce to the gaming world, you’ll receive exclusive bonuses. Your wins increase as the team gets bigger." },
      { "title": "Progress Bonus", "text": "Together, we can unlock incredible bonuses! With each referral, you’ll level up and see an increase in rewards. The benefits on your gaming journey increase with the number of friends you invite. Boost your development, go now!" },
      { "title": "Tax Commission", "text": "Presenting the Tax Commission for Referrals: get bonuses as you advance through the levels. Gain gaming perks, recommend friends, and level up with each victory. It’s a tax-free victory, not just a game!" }
    ],
    "image": "https://agents.teenpattistars.io/wp-content/uploads/2023/12/Big-agent-weekly-bonus-768x662.webp",
    "imageAlt": "Big agent weekly bonus"
  },
  "bigAgent": {
    "title": "How to Become a Big Agent",
    "intro": "You will employ diverse content marketing strategies to attract new users to the Teen Patti Stars Gaming Platform, and your earnings will be based on these efforts.",
    "items": [
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-4.webp", "alt": "", "title": "Registration", "text": "Simply fill out our user-friendly contact form first, providing essential details, such as your name, email address and phone number." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-5.webp", "alt": "", "title": "Video Content", "text": "You have the option to produce videos covering a range of subjects related to sports betting and live casinos." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-6.webp", "alt": "", "title": "Websites and Blogs", "text": "The distinctive code provided to you is embedded on this site, allowing your visitors to access the Teen Patti Stars Gaming Platform." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-7.webp", "alt": "", "title": "Social Media", "text": "Utilizing platforms such as Facebook, Twitter, and Instagram is an effective means to engage with online bettors." },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-8.webp", "alt": "", "title": "Email Marketing", "text": "You will be given a list of our games and links, which you will be promoting to players in your network using emails to promote" },
      { "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/output-onlinepngtools-9.webp", "alt": "", "title": "Bonuses and Rewards", "text": "You will earn more with every friend you bring on board! Refer and reap the rewards. Your bonus, your way." }
    ]
  },
  "partners": {
    "title": "Withdrawal Partners",
    "items": [
      { "name": "Paytm", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment-1.png" },
      { "name": "VISA", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment2.png" },
      { "name": "PayU", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment3.png" },
      { "name": "Mastercard", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment4.png" },
      { "name": "RuPay", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment5-1.png" },
      { "name": "UPI", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment6.png" },
      { "name": "PhonePe", "image": "https://agents.teenpattistars.io/wp-content/uploads/2024/01/payment7.png" }
    ]
  },
  "blog": {
    "title": "Blogs",
    "perPage": 9,
    "author": "Rosh"
  },
  "footer": {
    "disclaimerTitle": "DISCLAIMER",
    "disclaimer": [
      { "text": "Services not offered in Assam, Arunachal Pradesh, Andhra Pradesh, Telangana, Orissa & Nagaland. Games Suitable for 18 and above." },
      { "text": "Teen Patti Stars encourages all its players to play responsibly. Stay in control, stay entertained!." }
    ],
    "linksTitle": "QUICK LINKS",
    "links": [
      { "label": "Blogs", "url": "/blogs/" },
      { "label": "Big Agent India", "url": "/big-agent-india/" },
      { "label": "Teen Patti Rajasthan", "url": "/teen-patti-rajasthan/" },
      { "label": "Teen Patti Gujarat", "url": "/teen-patti-gujarat/" },
      { "label": "Teen Patti Bihar", "url": "/teen-patti-bihar/" },
      { "label": "Earning With Teen Patti", "url": "/earning-with-teen-patti-stars-in-india/" }
    ],
    "social": [
      { "label": "Facebook", "url": "https://www.facebook.com/teenpattistarsindia/", "icon": "facebook" },
      { "label": "Twitter", "url": "https://twitter.com/patti_stars", "icon": "twitter" },
      { "label": "Telegram", "url": "https://t.me/OfficialChannelTeenPattiStars", "icon": "telegram" },
      { "label": "Whatsapp", "url": "https://www.whatsapp.com/channel/0029VaCbmLb3mFYBIdhgJ90l", "icon": "whatsapp" }
    ],
    "copyright": "Copyright © {year} Teen Patti Stars | Powered by Teen Patti Star"
  },
  "socialBar": {
    "items": [
      { "label": "Telegram", "url": "https://t.me/OfficialChannelTeenPattiStars", "icon": "telegram" },
      { "label": "YouTube", "url": "https://www.youtube.com/", "icon": "youtube" },
      { "label": "Facebook", "url": "https://www.facebook.com/teenpattistarsindia/", "icon": "facebook" },
      { "label": "Instagram", "url": "https://www.instagram.com/", "icon": "instagram" },
      { "label": "WhatsApp", "url": "https://www.whatsapp.com/channel/0029VaCbmLb3mFYBIdhgJ90l", "icon": "whatsapp" }
    ]
  }
};
